# Generated by Django 3.1.4 on 2021-08-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='visa',
        ),
        migrations.AddField(
            model_name='contact',
            name='visa',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Visa',
        ),
    ]
