# Generated by Django 3.1.4 on 2021-07-09 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuidesPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GuidesPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('heading', models.CharField(max_length=500)),
                ('heading_outline_paragraph', models.CharField(max_length=1000)),
                ('pdf_image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('points', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guides.guidespoint')),
            ],
        ),
    ]
