# Generated by Django 3.1.4 on 2021-07-10 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_auto_20210709_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidespdf',
            name='guide_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='guidespdf',
            name='heading_outline_paragraph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='guidespoint',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='guides.guidespdf'),
        ),
    ]
