# Generated by Django 3.1.4 on 2021-07-10 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guides', '0005_auto_20210710_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidesForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('buisness_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=100)),
                ('website_url', models.URLField()),
                ('phone_number', models.CharField(max_length=20)),
                ('employes', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
