# Generated by Django 3.1.4 on 2021-07-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0008_auto_20210718_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidesform',
            name='employes',
            field=models.CharField(max_length=100),
        ),
    ]
