# Generated by Django 3.1.4 on 2021-07-25 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidesPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('heading', models.CharField(max_length=500)),
                ('heading_outline_paragraph', models.TextField()),
                ('pdf_image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('guide_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='GuidesPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=200)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='resources.guidespdf')),
            ],
        ),
        migrations.CreateModel(
            name='GuidesForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('buisness_email', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('website_url', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('employes', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
