# Generated by Django 3.1.4 on 2021-08-15 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidesResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_title', models.CharField(max_length=200)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('heading', models.CharField(max_length=500)),
                ('heading_outline_paragraph', models.TextField()),
                ('guide_pdf', models.FileField(upload_to='')),
                ('heading_image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='guidespoint',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='resources.guidesresources'),
        ),
        migrations.DeleteModel(
            name='GuidesPdf',
        ),
    ]
