# Generated by Django 3.1.4 on 2021-08-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210815_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidesresources',
            name='guide_pdf',
            field=models.FileField(upload_to='guide_pdf'),
        ),
        migrations.AlterField(
            model_name='guidesresources',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='guide_thumbnail'),
        ),
    ]
