# Generated by Django 3.1.4 on 2021-08-16 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20210815_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidesresources',
            name='guide_pdf',
            field=models.FileField(upload_to='guide_pdf', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
