# Generated by Django 3.1.4 on 2020-12-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=5000)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
