# Generated by Django 3.1.4 on 2021-06-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_auto_20210613_0130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'User Message', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
