# Generated by Django 3.1.4 on 2021-07-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_auto_20210613_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Visa Application',
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='visa',
        ),
        migrations.AddField(
            model_name='contact',
            name='visa',
            field=models.ManyToManyField(to='contactus.Visa'),
        ),
    ]
