# Generated by Django 3.1.4 on 2021-07-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0004_auto_20210717_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='visa',
            field=models.ManyToManyField(blank=True, null=True, to='contactus.Visa'),
        ),
    ]
